# Generated by Django 4.2.26 on 2025-12-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=200),
        ),
    ]
